### ISSUE TITLE
sns.jointplot mit zeitlichen Zusammenhang nicht korrekt (ix-jupyter-visualisierung-2.ipynb)

### ISSUE THREAD

**Issue by Michael-Schulze** [datanizing/ix-jupyter-visualisierung#1]
Ich bekomme Fehler und fehlerhafte Anzeige im ix-jupyter-visualisierung-2.ipynb bei dem sns.jointplot. Im ix Artikel Datenvisualisierung mit Jupyter-Notebook Teil2 (ix 2/2021 Seite 133 Listing 3).

Zum einen scheint es ein Problem mit mit Wurzel aus ungültigen Werten zu geben, zum anderen werden die Punkte nicht im Hauptplot gezeigt, sondern im  seitlichen Balkendiagramm.

Ich habe es mit Python 3.8 probiert, sowie im Colab (Python 3.6.9) des ersten Artikels (https://colab.research.google.com/github/datanizing/ix-jupyter-visualisierung/blob/main/ix-jupyter-visualisierung-1.ipynb#scrollTo=1ynnGAHU6AET) mit kopierten Code aus der ix. Beide Varianten klappen nicht

![Screenshot from 2021-01-26 14-33-41](https://user-images.githubusercontent.com/28435324/105851987-1ede4f00-5fe4-11eb-895a-95ba398cabe9.png)

**Comment by datanizing** [comment]
Danke für den Hinweis. Die Fehlermeldung ist eine Warnung, die durch die Größe der Bubbles entsteht und kann ignoriert werden.

Die Darstellung ist aber definitiv falsch. Leider gibt es in `seaborn` häufig Änderungen, die nicht rückwärtskompatibel sind - so auch hier. Zum Zeitpunkt der Erstellung des Artikels war seaborn 0.11.0 aktuell, seaborn 0.11.1 macht wieder einiges anders. 

Der Fehler ist nun korrigiert bzw. seaborn wird nun in Version 0.11.0 installiert. Entschuldigung für die Umstände.

**Comment by Michael-Schulze** [comment]
Bei dem Fix ist eine Zeile Code verschwunden ... `de20s = de20[de20.index.month==1].copy()`

Wenn ich es von Hand hinzufüge, dann klappt es nun.

```
import matplotlib.pyplot as plt
g = sns.jointplot(x=de20["BS-SFSH"], y=de20["BS-CSMCI"], scatter=False, kind="reg")
# aktuelle Ersparnisse als Größe der Bubbles
# take only first month
de20s = de20[de20.index.month==1].copy()
# take every other year
de20s = de20s[::2]
# remove M01 from index
de20s.index = de20s.index.map(str).str.replace("-01-01 00:00:00", "")
sns.scatterplot(x=de20s["BS-SFSH"], y=de20s["BS-CSMCI"], s=de20s["BS-SV-PR"],
                hue=de20s.index, legend=True)
# Detailplot ohne Legende
sns.scatterplot(x=de20["BS-SFSH"], y=de20["BS-CSMCI"], s=de20["BS-SV-PR"],
                hue=de20.index, legend=False)
plt.gca().annotate("pearsonr=%0.2f p=%e"%stats.pearsonr(de20["BS-SFSH"], de20["BS-CSMCI"]), xy=(5, -25))
```

![image](https://user-images.githubusercontent.com/28435324/106301463-09715b00-6258-11eb-8fc6-453f88ffeb79.png)

**Comment by datanizing** [comment]
Danke für den Hinweis, jetzt läuft es auf Colab durch
